name = "Tiny Tater Test server (AOF)"
author = "Tiny Taters, Team AOF"
version = "2.2.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b32382903542be41bc8f1f32b78a62c76ccf9137bce39539bb573675ecebcd9f"

[versions]
fabric = "0.11.1"
minecraft = "1.16.5"
