name = "Tiny Tater Test server (AOF)"
author = "Tiny Taters, Team AOF"
version = "2.2.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "59948502699b6c34441f9efdd1dc0bf9e285daf482dae37f0d88e39e1600ca33"

[versions]
fabric = "0.11.1"
minecraft = "1.16.5"
