name = "Tiny Tater Test server (AOF)"
author = "Tiny Taters, Team AOF"
version = "2.2.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0b9d75dc5f419c20e5cc28c59e7109fb037cf0ce1899a4fc1ee1ae61134f70c4"

[versions]
fabric = "0.11.1"
minecraft = "1.16.5"
