name = "Tiny Tater Test server (AOF)"
author = "Tiny Taters, Team AOF"
version = "2.2.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8bad5f582d3b4f28af9309ab31460f479fd19c99ca453c20074edf3e1af11db7"

[versions]
fabric = "0.11.1"
minecraft = "1.16.5"
