name = "Tiny Tater Test server (AOF)"
author = "Tiny Taters, Team AOF"
version = "2.1.3"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d02056d117311cb9ce140bc012769ff628a5052f1dcd3cad6b79809691ec2b2d"

[versions]
fabric = "0.11.1"
minecraft = "1.16.5"
