name = "Tiny Tater Test server (AOF)"
author = "Tiny Taters, Team AOF"
version = "2.2.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bfec21580e519882c3264832b1a6da9eb3dff248449e95a6ee90fb09d0e926b5"

[versions]
fabric = "0.11.1"
minecraft = "1.16.5"
