name = "Applied Energistics 2"
filename = "appliedenergistics2-fabric-8.3.0-alpha.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3311/900/appliedenergistics2-fabric-8.3.0-alpha.2.jar"
hash-format = "murmur2"
hash = "2292454662"

[update]
[update.curseforge]
file-id = 3311900
project-id = 223794
release-channel = "beta"
