name = "Architectury API (Fabric)"
filename = "architectury-1.14.156-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3309/827/architectury-1.14.156-fabric.jar"
hash-format = "murmur2"
hash = "2349372742"

[update]
[update.curseforge]
file-id = 3309827
project-id = 419697
release-channel = "beta"
