name = "BetterEnd"
filename = "better-end-0.9.6-pre.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3300/748/better-end-0.9.6-pre.jar"
hash-format = "murmur2"
hash = "1260173646"

[update]
[update.curseforge]
file-id = 3300748
project-id = 413596
release-channel = "beta"
