name = "Builtin Servers"
filename = "builtin-servers-1.0-BETA.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3280/130/builtin-servers-1.0-BETA.jar"
hash-format = "murmur2"
hash = "2775565191"

[update]
[update.curseforge]
file-id = 3280130
project-id = 473131
release-channel = "beta"
