name = "Cloth Config API (Fabric)"
filename = "cloth-config-4.11.26-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3311/351/cloth-config-4.11.26-fabric.jar"
hash-format = "murmur2"
hash = "881430275"

[update]
[update.curseforge]
file-id = 3311351
project-id = 319057
release-channel = "beta"
