name = "Dynamic FPS"
filename = "dynamic-fps-2.0.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3302/730/dynamic-fps-2.0.2.jar"
hash-format = "murmur2"
hash = "1527704295"

[update]
[update.curseforge]
file-id = 3302730
project-id = 335493
release-channel = "beta"
