name = "Enchantment Descriptions"
filename = "EnchantmentDescriptions-fabric-1.16.5-2.0.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3276/195/EnchantmentDescriptions-fabric-1.16.5-2.0.2.jar"
hash-format = "murmur2"
hash = "1851420847"

[update]
[update.curseforge]
file-id = 3276195
project-id = 250419
release-channel = "beta"
