name = "Fabric Language Kotlin"
filename = "fabric-language-kotlin-1.6.0+kotlin.1.5.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3300/699/fabric-language-kotlin-1.6.0+kotlin.1.5.0.jar"
hash-format = "murmur2"
hash = "2455042968"

[update]
[update.curseforge]
file-id = 3300699
project-id = 308769
release-channel = "beta"
