name = "Fabric API"
filename = "fabric-api-0.34.2+1.16.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3304/636/fabric-api-0.34.2+1.16.jar"
hash-format = "murmur2"
hash = "3119244747"

[update]
[update.curseforge]
file-id = 3304636
project-id = 306612
release-channel = "beta"
