name = "FlytreLib"
filename = "flytre_lib-0.2.10.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3305/8/flytre_lib-0.2.10.jar"
hash-format = "murmur2"
hash = "1662949508"

[update]
[update.curseforge]
file-id = 3305008
project-id = 444498
release-channel = "beta"
