name = "GeckoLib [FABRIC]"
filename = "geckolib-fabric-1.16.5-3.0.34.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3301/110/geckolib-fabric-1.16.5-3.0.34.jar"
hash-format = "murmur2"
hash = "466702336"

[update]
[update.curseforge]
file-id = 3301110
project-id = 398667
release-channel = "beta"
