name = "Gunpowder"
filename = "gunpowder-base-0.5.6+1.16.5.jar"
side = "server"

[download]
url = "https://edge.forgecdn.net/files/3307/292/gunpowder-base-0.5.6+1.16.5.jar"
hash-format = "murmur2"
hash = "4081689174"

[update]
[update.curseforge]
file-id = 3307292
project-id = 350123
release-channel = "beta"
