name = "megane"
filename = "megane-4.0.0+1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3310/590/megane-4.0.0+1.16.5.jar"
hash-format = "murmur2"
hash = "3543502673"

[update]
[update.curseforge]
file-id = 3310590
project-id = 408118
release-channel = "beta"
