name = "Modern Industrialization"
filename = "Modern-Industrialization-0.3.17.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3291/171/Modern-Industrialization-0.3.17.jar"
hash-format = "murmur2"
hash = "3152080989"

[update]
[update.curseforge]
file-id = 3291171
project-id = 405388
release-channel = "beta"
