name = "Pehkui"
filename = "Pehkui-2.1.0+21w18a.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3300/900/Pehkui-2.1.0+21w18a.jar"
hash-format = "murmur2"
hash = "203634807"

[update]
[update.curseforge]
file-id = 3300900
project-id = 319596
release-channel = "beta"
