name = "Phosphor (Fabric)"
filename = "phosphor-fabric-mc1.16.3-0.7.2+build.12.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3294/303/phosphor-fabric-mc1.16.3-0.7.2+build.12.jar"
hash-format = "murmur2"
hash = "1912698651"

[update]
[update.curseforge]
file-id = 3294303
project-id = 372124
release-channel = "beta"
