name = "Repurposed Structures (Fabric)"
filename = "repurposed_structures-1.16.5-1.10.5-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3295/7/repurposed_structures-1.16.5-1.10.5-fabric.jar"
hash-format = "murmur2"
hash = "1992353439"

[update]
[update.curseforge]
file-id = 3295007
project-id = 391366
release-channel = "beta"
