name = "Roughly Enough Items Fabric (REI)"
filename = "RoughlyEnoughItems-5.11.218.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3283/816/RoughlyEnoughItems-5.11.218.jar"
hash-format = "murmur2"
hash = "1327075179"

[update]
[update.curseforge]
file-id = 3283816
project-id = 310111
release-channel = "beta"
