name = "Secret Rooms Fabric"
filename = "secretrooms-0.9.5+1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3301/647/secretrooms-0.9.5+1.16.5.jar"
hash-format = "murmur2"
hash = "3468357005"

[update]
[update.curseforge]
file-id = 3301647
project-id = 359248
release-channel = "beta"
