name = "Vanilla Hammers"
filename = "vanilla-hammers-3.0.3-1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3284/894/vanilla-hammers-3.0.3-1.16.5.jar"
hash-format = "murmur2"
hash = "4035645740"

[update]
[update.curseforge]
file-id = 3284894
project-id = 317756
release-channel = "beta"
