name = "Winged"
filename = "winged-1.16.5-2.0.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3301/434/winged-1.16.5-2.0.5.jar"
hash-format = "murmur2"
hash = "235561791"

[update]
[update.curseforge]
file-id = 3301434
project-id = 381349
release-channel = "beta"
