name = "Wolves With Armor"
filename = "wolves-with-armor-1.5.4-1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3284/827/wolves-with-armor-1.5.4-1.16.5.jar"
hash-format = "murmur2"
hash = "1762803663"

[update]
[update.curseforge]
file-id = 3284827
project-id = 375969
release-channel = "beta"
