name = "WTHIT"
filename = "wthit-2.10.0-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3309/397/wthit-2.10.0-fabric.jar"
hash-format = "murmur2"
hash = "3953235552"

[update]
[update.curseforge]
file-id = 3309397
project-id = 440979
release-channel = "beta"
