name = "Xaero's Minimap"
filename = "Xaeros_Minimap_21.8.1_Fabric_1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3307/171/Xaeros_Minimap_21.8.1_Fabric_1.16.5.jar"
hash-format = "murmur2"
hash = "1160276934"

[update]
[update.curseforge]
file-id = 3307171
project-id = 263420
release-channel = "beta"
