name = "Xaero's World Map"
filename = "XaerosWorldMap_1.13.5_Fabric_1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3307/185/XaerosWorldMap_1.13.5_Fabric_1.16.5.jar"
hash-format = "murmur2"
hash = "4180839639"

[update]
[update.curseforge]
file-id = 3307185
project-id = 317780
release-channel = "beta"
