name = "YUNG's Better Caves (Fabric)"
filename = "BetterCaves-Fabric-1.16.5-1.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3307/522/BetterCaves-Fabric-1.16.5-1.2.jar"
hash-format = "murmur2"
hash = "1312106615"

[update]
[update.curseforge]
file-id = 3307522
project-id = 408465
release-channel = "beta"
